spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      validation-timeout: 10000
      maxLifetime: 1790000
  jpa:
    # https://stackoverflow.com/questions/37066024/what-is-the-mariadb-dialect-class-name-for-hibernate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate:
      default_batch_fetch_size: 100
      format_sql: true
      show_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  jwt:
    secret: VyAHb65Ww8V1vj2FXHMS6g==

  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 50MB
  config:
    import: optional:file:.env[.properties]
  data:
    jpa:
      repositories:
        enabled: true
        auditing:
          enabled: true
  batch:
    jdbc.initialize-schema: always
    job:
      enabled: false
